### ISSUE TITLE
Unable to use on the Android side? 

### ISSUE THREAD

**Issue by 2188886665** [AstrozTM/String-Protector#1]
this js  'require'( xxx) Writing method It doesn't seem right   not find       How can I contact you    If you have a plan to protect the lua code, I can buy it

**Comment by AstrozTM** [comment]
If you want to protect your lua code, I'd recommend https://psu.dev/upgrade.
Really good obfuscator, if you use it with my method too it increases the
difficulty of constant dumping, the script.

Thanks for contacting me!

**Comment by 2188886665** [comment]
Yes, I joined bot, but I don't get it. Why doesn't the robot process the files I upload?
